version: '3'
services:
  mlflow:
    build:
      context: deployment/mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    entrypoint: mlflow
    command:
      - server
      - --backend-store-uri=sqlite:////mlflow/mlflow.db
      - --default-artifact-root=/mlflow/artifacts
      - --host=0.0.0.0
      - --port=5000
  jupyter:
    build: 
      context: deployment/jupyter
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/mlflow-demo
    entrypoint: start.sh
    environment: 
      MLFLOW_TRACKING_URI: 127.0.0.1:5000    
    command:
      - jupyter
      - lab
      - --host=0.0.0.0

