version: '3'
services:
  mlflow:
    build:
      context: deployment/mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    entrypoint: mlflow
    # Note that --default-artifact-root should be set as seen from client
    command:
      - server
      - --backend-store-uri=sqlite:////mlflow/mlflow.db
      - --default-artifact-root=file:///mlflow/artifacts
      - --host=0.0.0.0
      - --port=5000
  jupyter:
    build:
      context: deployment/jupyter
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/mlflow-demo
      - ./mlflow:/mlflow
    entrypoint: start.sh
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    command:
      - jupyter
      - lab
      - --host=0.0.0.0

